### ISSUE TITLE
Problem with controller

### ISSUE THREAD

**Issue by lucumon** [aadfPT/MiControllerPluginForInputMapper#1]
Sorry if I'm doing something wrong, but when I select Xiaomi Bluetooth Wireless GameController for maping, nothing is working, but when I select this gamepad with the Directinput plugin, a few buttons work, but not all.
Also, the program tells me that is a new update of this plugin (1.0.0.4), and when I click update, it downloads again 1.0.0.3

Please help, and god job

P.D.: Sorry for my bad english, but I'm a spanish 16 years old boy

**Comment by aadfPT** [comment]
Hi Nikos, there are better solutions now (InputMapper is still under development).
Instead of using this, you can use https://github.com/dancol90/mi-360
